env:
  - GHCVER=7.8.3
  - GHCVER=head

before_install:
  - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
  - travis_retry sudo apt-get update
  - travis_retry sudo apt-get install cabal-install-1.20 ghc-$GHCVER happy
  - export PATH=/opt/ghc/$GHCVER/bin:$PATH
  - sudo ln -s `which cabal-1.20` /usr/bin/cabal
install:
  - cabal-1.20 update
  - cabal-1.20 install --only-dependencies --enable-tests --enable-benchmarks -j2

script:
  - cabal-1.20 configure --enable-tests --enable-benchmarks -v2
  - cabal-1.20 build
  - cabal-1.20 test
  - cabal-1.20 check
  - cabal-1.20 sdist
  - export SRC_TGZ=$(cabal-1.20 info . | awk '{print $2 ".tar.gz";exit}') ; 
    cd dist/;
    if [ -f "$SRC_TGZ" ]; then 
      cabal-1.20 install "$SRC_TGZ"; 
    else 
      echo "expected '$SRC_TGZ' not found"; 
      exit 1; 
    fi

matrix:
  allow_failures:
    - env: GHCVER=head

