language: c
sudo: false

cache:
  directories:
    - $HOME/.stack

matrix:
  include:
    - env: STACK_YAML=stack.yaml
      compiler: ": #GHC 8.0.1"
      addons:
        apt:
          packages:
            - libgmp3-dev
    - env: STACK_YAML=stack-head.yaml
      compiler: ": #GHC HEAD"
      addons:
        apt:
          packages:
            - libgmp3-dev
  allow_failures:
    - env: STACK_YAML=stack-head.yaml

before_install:
 # install Stack
 - mkdir -p ~/.local/bin
 - export PATH=$HOME/.local/bin:$PATH
 - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
 - unset CC
 - export PATH=$HOME/.local/bin:$PATH
 - stack setup

install:
 - stack --version
 - stack build --only-dependencies

# Here starts the actual work to be performed for the package under test;
# any command which exits with a non-zero exit code causes the build to fail.
script:
 -  stack --no-terminal --skip-ghc-check test

# Check that the resulting source distribution can be built & installed.
# If there are no other `.tar.gz` files in `dist`, this can be even simpler:
# `cabal install --force-reinstalls dist/*-*.tar.gz`
# EOF
