resolver: nightly-2016-08-02
packages:
- '.'
build: 
  haddock: true
extra-deps:
- type-natural-0.6.0.0
- equational-reasoning-0.4.0.0
- monomorphic-0.0.3.3
- singletons-2.2
- ghc-typelits-presburger-0.1.1.0
- th-desugar-1.6
